---
- hosts: 127.0.0.1
  sudo: yes
  vars:
    - ruby_version: 2.2.2
  tasks:
    - name: yum update
      yum: name=* state=latest
    - name: disable iptables
      service: name=iptables state=stopped enabled=no
    - name: install libselinux-python
      yum: name=libselinux-python state=latest
    - name: install remi repository
      command: rpm -Uvh --force http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    - name: install ruby dependencies
      yum: name={{item}} enablerepo=remi,epel state=present
      with_items:
        - gcc
        - openssl-devel
        - rpm-build
        - gcc-c++
        - bzip2
        - libtool
        - zlib
        - zlib-devel
        - httpd-devel
        - openssl-devel
        - curl-devel
        - ncurses-devel
        - gdbm-devel
        - readline
        - readline-devel
        - sqlite-devel
        - libyaml-devel
        - libffi-devel
        - bison

    - name: check rbenv installed
      command: test -x /root/.rbenv
      register: rbenv_present
      ignore_errors: yes
      sudo: no
    - name: git clone rbenv
      git: repo=https://github.com/sstephenson/rbenv.git dest=/root/.rbenv
      when: rbenv_present.rc != 0
      sudo: no
    - name: update bash_profile
      copy: src=bash_profile.custom dest=/root/.bash_profile backup=yes
      sudo: no 

    - name: check ruby-build installed
      command: test -x /root/.rbenv/plugins/ruby-build
      register: rbuild_present
      ignore_errors: yes
      sudo: no
    - name: git clone ruby-build
      git: repo=https://github.com/sstephenson/ruby-build.git dest=/root/.rbenv/plugins/ruby-build
      when: rbuild_present.rc != 0
      sudo: no

    - name: check ruby installed
      shell: /bin/bash -lc "rbenv versions | grep {{ruby_version}}"
      register: ruby_installed
      ignore_errors: yes
      sudo: no
    - name: install ruby
      shell: /bin/bash -lc "rbenv install {{ruby_version}} && rbenv rehash && rbenv global {{ruby_version}}"
      when: ruby_installed.rc != 0
      sudo: no

    - name: check node js installed
      shell: /bin/bash -lc "node -v"
      register: node_installed
      ignore_errors: yes
      sudo: no
    - name: install node script
      shell: /bin/bash -lc "curl -sL https://rpm.nodesource.com/setup | bash -"
      when: node_installed.rc != 0
    - name: install nodejs
      yum: name=nodejs state=latest
      when: node_installed.rc != 0


